<?php
require "model/bithudoankhoa.php";
require "model/bocauhoi.php";
require "model/dieu.php";
require "model/dotchamdiem.php";
require "model/giangvien.php";
require "model/hocky.php";
require "model/ketquaxeploai.php";
require "model/khoa.php";
require "model/khoahoc.php";
require "model/khoan.php";
require "model/lopapdung.php";
require "model/lophoc.php";
require "model/mauphieu.php";
require "model/minhchung.php";
require "model/muc.php";
require "model/namhoc.php";
require "model/nganhhoc.php";
require "model/phancong.php";
require "model/phannhom.php";
require "model/phanquyen.php";
require "model/phieuchamdiem.php";
require "model/sinhvien.php";
require "model/taikhoan.php";
require "model/trinhdo.php";
require "model/xeploai.php";
require "model/hashpassword.php";
require "model/yeucaukichhoat.php";

$bithudoankhoa = new bithudoankhoa();
$bocauhoi = new bocauhoi();
$dieu = new dieu();
$dotchamdiem = new dotchamdiem();
$giangvien = new giangvien();
$hocky = new hocky();
$ketquaxeploai = new ketquaxeploai();
$khoa = new khoa();
$khoahoc = new khoahoc();
$khoan = new khoan();
$lopapdung = new lopapdung();
$lophoc = new lophoc();
$mauphieu = new mauphieu();
$minhchung = new minhchung();
$muc = new muc();
$namhoc = new namhoc();
$nganhhoc = new nganhhoc();
$phancong = new phancong();
$phannhom = new phannhom();
$phanquyen = new phanquyen();
$phieuchamdiem = new phieuchamdiem();
$sinhvien = new sinhvien();
$taikhoan = new taikhoan();
$trinhdo = new trinhdo();
$xeploai = new xeploai();
$hashpassword = new hashpassword();
$yeucaukichhoat = new yeucaukichhoat();
